# Generated by Django 5.2 on 2025-05-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_customuser_address_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('session_type', models.CharField(choices=[('career', 'Career Guidance'), ('academic', 'Academic Help'), ('wellness', 'Mental Wellness')], max_length=20)),
                ('mentor_preference', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('mode_of_session', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
