# Generated by Django 5.2 on 2025-05-13 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_mentorshipsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorshipsession',
            name='mentor_preference',
        ),
    ]
