# Generated by Django 5.2 on 2025-05-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_material_delete_uploadedcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('course_tag', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
