# Generated by Django 5.2 on 2025-05-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_courses_material_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshipsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=10),
        ),
    ]
