# Generated by Django 5.2 on 2025-05-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_mentorshipsession_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='totalcourse',
        ),
    ]
